services:

  melonsort:
    build: 
      dockerfile: ./image/dockerfile
    env_file: .env
    volumes:
      - ./src:/srv/melonsort:shared
      - /mnt/d/wavs:/wavs:shared
      - hf:/hf
      - data:/data
      - embeds:/embeds
    ports:
      - 80:80
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  hf:
  data:
  embeds:
