FROM python:3.10.14-slim-bookworm

WORKDIR /srv/train

# General setup
COPY images/sort/apt-dependencies.txt ./
RUN apt-get update && apt-get install -y $(cat apt-dependencies.txt)
RUN mkdir /laion

RUN git clone https://github.com/mxkopy/CLAP /laion/CLAP
RUN git clone https://github.com/LAION-AI/audio-dataset.git /laion/audio-dataset

RUN \
    --mount=type=cache,target=/var/cache/apt \
    --mount=type=cache,target=/root/.cache \
    pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0+cu113 -f https://download.pytorch.org/whl/torch_stable.html

# Installs other dependencies
COPY images/sort/py-dependencies.txt ./
RUN pip install --upgrade --no-cache-dir -r py-dependencies.txt

RUN cd /laion/CLAP && pip install --force-reinstall .


CMD [ "fastapi", "dev", "train.py", "--port", "80", "--host", "0.0.0.0" ]
